#!/bin/bash
echo -en "\0prompt\x1fBookmarks\n*"

export FIREFOX_PROFILE="*.default-release"

SQL="SELECT b.title || \" | \" ||  p.url  FROM moz_bookmarks b JOIN moz_places p ON b.fk = p.id WHERE b.fk is not null AND b.title <> '' AND url <> '' AND url NOT LIKE 'place:%'"

if [ -z "${FIREFOX_PROFILE+x}" ]; then
    echo "FIREFOX_PROFILE not set"
    exit 1
fi

PROFILE_DB=~/.mozilla/firefox/${FIREFOX_PROFILE}/places.sqlite
TMP_PLACES=/tmp/places

cp -f ${PROFILE_DB} ${TMP_PLACES}
ENTRIES=$(sqlite3 ${TMP_PLACES} "${SQL}")

if [ -z "$1" ]; then
    IFS=' | '
    echo "${ENTRIES}"
    read -ra ADDR <<<"$ENTRIES"
    for i in "${ADDR[@]}"; do
        URL=$i
    done
    echo "$URL"
else
    URL=$1
    URL2=$(echo "$URL" | sed -n 's/^.*http/http/p')
    firefox "$URL2"
    exit 0
fi

rm ${TMP_PLACES}
