#!/bin/sh

# Attach to tmux if session exists, else new session

if command -v tmux >/dev/null 2>&1; then
    tmux attach || tmux >/dev/null 2>&1
else
    echo "tmux is not installed"
    "$SHELL"
fi
